# Test against this version of Node.js
language: node_js
node_js:
  - "0.12"

sudo: required

branches:
  only:
    # only tags on the form vx.x.x or vx.x.xxx and so on
    - /v\d+\.\d+\.\d+/

# Install scripts.
install:
  # Install meteor
  - curl https://install.meteor.com/ | /bin/sh
  # setup ElectronMeteor
  - npm run setup

script:
  # Pack and build
  - npm run pack:linux
  # zip it up
  # Linux
  - tar -zcf ElectronMeteor-v${TRAVIS_TAG}-linux-x86.tar.gz dist/linux/x86/ElectronMeteor-linux-x86
  # Windows
  # - tar -zcf ElectronMeteor-v${TRAVIS_TAG}-win32-ia32.tar.gz dist/windows/ElectronMeteor-win32-ia32
  # - tar -zcf ElectronMeteor-v${TRAVIS_TAG}-win32-ia32-installer.tar.gz dist/windows/ElectronMeteor\ Setup.exe
  # Mac
  # - tar -zcf ElectronMeteor-v${TRAVIS_TAG}-darwin-x64.tar.gz dist/linux/ElectronMeteor.dmg

deploy:
  provider: releases
  api_key: "c84e543eaa4e8315483285da7e40f8a18c7330df"
  file:
    - "ElectronMeteor-v${TRAVIS_TAG}-linux-x86.tar.gz"
    # - "ElectronMeteor-v${TRAVIS_TAG}-win32-ia32.tar.gz"
    # - "ElectronMeteor-v${TRAVIS_TAG}-win32-ia32-installer.tar.gz"
    # - "ElectronMeteor-v${TRAVIS_TAG}-darwin-x64.tar.gz"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
