# Test against this version of Node.js
environment:
  nodejs_version: "0.12"

# clone directory
clone_folder: C:\gv

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Setup
  - npm run setup
  # download Meteor
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # install meteor
  - .\installMeteor.exe /passive
  # download NSIS
  - ps: choco install nsis.install -pre
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force

build_script:
  - ps: Start-Sleep -s 5
  - npm run pack:win

cache:
  - cache

deploy:
  provider: GitHub
  auth_token:
    secure: 4DLKG48sJhZ2Xbr/ulNR4MUEaVVc/ps6WhTD5OvxgGE5TErcKYH/uuCD3ogw7cfL
  artifact: "grandview-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32,grandview-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32-installer"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: dist\windows\x86\ElectronMeteor-win32-ia32
    name: grandview-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32

  - path: dist\windows\x86\ElectronMeteor Setup.exe
    name: grandview-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32-installer
