environment:
  nodejs_version: "0.10.36"

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Setup
  - npm install
  # download Meteor
  - ps: Start-FileDownload 'https://s3.amazonaws.com/meteor-windows/InstallMeteor.exe'
  # install meteor
  - .\installMeteor.exe /passive
  # download NSIS
  - ps: choco install -y nsis -pre
  # Restart
  - ps: Start-Sleep -s 5
  - ps: Restart-Computer -Force

build_script:
  - ps: Start-Sleep -s 5
  - set PATH=C:\Program Files (x86)\NSIS;%PATH%
  - npm i electron-packager -g
  - node scripts/download --platform=win32 --arch=x86
  - node scripts/prepare --platform=win32 --arch=x86
  - electron-packager ./app "ElectronMeteor" --out=dist/windows/x86 --platform=win32 --arch=ia32 --version=0.27.2 --icon=assets/icons/electronmeteor.ico --ignore="node_modules/(shelljs|colors|adm-zip|tar|gunzip-maybe|rimraf|minimist|electron-packager|electron-builder|electron-prebuilt|electron-rebuild)
  #- npm run build:win
  # Update node
  - ps: Update-NodeJsInstallation 0.12.7
  - npm run pack:win

after_build:
  - 7z a ElectronMeteor-win32-ia32-installer.zip "%APPVEYOR_BUILD_FOLDER%\dist\windows\x86\ElectronMeteor Setup.exe"

deploy:
  provider: GitHub
  auth_token:
    secure: 4DLKG48sJhZ2Xbr/ulNR4MUEaVVc/ps6WhTD5OvxgGE5TErcKYH/uuCD3ogw7cfL
  artifact: "ElectronMeteor-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32,ElectronMeteor-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32-installer"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: dist\windows\x86\ElectronMeteor-win32-ia32
    name: ElectronMeteor-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32

  - path: ElectronMeteor-win32-ia32-installer.zip
    name: ElectronMeteor-$(APPVEYOR_REPO_TAG_NAME)-win32-ia32-installer
